### ISSUE TITLE
HTMLCanvasElement.toBlob() signature is incorrect

### ISSUE THREAD

**Issue by elisee** [Microsoft/TSJS-lib-generator#104]
I believe the function signature for `HTMLCanvasElement.toBlob()` is wrong. According to https://developer.mozilla.org/en-US/docs/Web/API/HTMLCanvasElement/toBlob, it is async and takes a callback plus optional media type / quality option arguments.

See #45.

**Comment by mhegazy** [comment]
From the spec: https://www.w3.org/TR/html5/scripting-1.html#dom-canvas-toblob, the signature should be:
```ts
toBlob(callback: (result: Blob | null) => void, ... arguments: any[]): void;
```

**Comment by mhegazy** [comment]
PRs are welcomed.
