### ISSUE TITLE
insertAdjacent* methods should be part of the Element interface

### ISSUE THREAD

**Issue by davidkmenta** [Microsoft/TSJS-lib-generator#130]
TypeScript Version: 1.8.10

Expected behavior: According to the MDN (https://developer.mozilla.org/en-US/docs/Web/API/Element), insertAdjacent* methods should be part of the Element interface.

Actual behavior: insertAdjacent* methods are part of the HTMLElement interface.

**Comment by mhegazy** [comment]
This issue was moved to Microsoft/TypeScript#9617
