### ISSUE TITLE
WeakMap remove `.clear()`?

### ISSUE THREAD

**Issue by kitsonk** [Microsoft/TSJS-lib-generator#145]
From Microsoft/TypeScript#10695, for some reason TSJS-lib-generator is picking up `.clear()` on WeakMap, though the ChakraCore team indicate it is not exposed to JavaScript land (see Microsoft/TypeScript#1539)

**Comment by zhengbli** [comment]
`lib.es6.d.ts` is not generated by the tool in this repo, it is hand-written instead. This issue should be fixed in the TS main repo.
