### ISSUE TITLE
Support UrlSearchParams

### ISSUE THREAD

**Issue by shaunluttin** [Microsoft/TSJS-lib-generator#153]
https://github.com/DefinitelyTyped/DefinitelyTyped/issues/9378

To quote @ryan-codingintrigue:

> ...global definitions like [UrlSearchParams] should be in TypeScript's lib.d.ts definition
> (See https://github.com/Microsoft/TypeScript/blob/master/src/lib/dom.generated.d.ts#L11759)
> 
> But they only go into that once Microsoft Edge supports the feature and at present, URLSearchParams is not present in Edge.

**Comment by mhegazy** [comment]
PRs are welcomed.
