### ISSUE TITLE
Can't chain HTMLElement.offsetParent property

### ISSUE THREAD

**Issue by andrewiggins** [Microsoft/TSJS-lib-generator#156]
In browser.webidl.xml, HTMLElement.offsetParent has type Element. Type Element does not have an offsetParent property. Therefore it is not possible to chain offsetParent properties in Typescript like such as `htmlelement.offsetParent.offsetParent`.

This capability seems to broadly supported as the [jQuery source](http://ajax.googleapis.com/ajax/libs/jquery/1/jquery.js) uses this in its position function (CTRL+F for `offsetParent:` to find it).

Obviously the workaround is to cast the offsetParent property to HTMLElement. Not sure how easy this is to fix since browser.webidl.xml is from the Edge team, but regardless I thought I would call it out here.

Latest Edge does appear to support chaining calls to offsetParent in my tests.

**Comment by mhegazy** [comment]
I could not find anything in the spec that says it should be an HTMLElement and not Element, keep in mind that SVGElements are Elements but not HTMLElements. do you have a pointer to the spec that indicates that?

**Comment by andrewiggins** [comment]
Ah true, I forget about SVGElements. I'll close this as I don't have any real evidence per the spec. Thanks for looking.
