### ISSUE TITLE
Missing Attr.isId

### ISSUE THREAD

**Issue by lord-saumagen** [Microsoft/TSJS-lib-generator#161]
TypeScript Version: 1.8.0

Dear Ladies and Gentlemen,

I would like to bring to your attention, that the following function / property is not defined in the "lib.es6.d.ts".

Attr.isId

The Attr.IsId is defined in the DOM-Leve3-Core specification which is available at the W3C.

[W3C DOM Level3 Core](https://www.w3.org/TR/2003/WD-DOM-Level-3-Core-20030609/core.html#ID-637646024)

![w3c_isid](https://cloud.githubusercontent.com/assets/9468599/19526962/7a834fcc-9626-11e6-9eb2-deecb505cfaf.png)

Here is the part of the "lib.es6.d.ts" which declares the "Attr" object.

![lib es6 d ts_isid](https://cloud.githubusercontent.com/assets/9468599/19526986/a008496e-9626-11e6-826e-1231bba507db.png)

Kind regards, Lord Saumagen.

**Comment by mhegazy** [comment]
PRs welcomed. You can find more information about contributing lib.d.ts fixes at https://github.com/Microsoft/TypeScript/blob/master/CONTRIBUTING.md#contributing-libdts-fixes.

**Comment by SaschaNaz** [comment]
It seems this is removed on [WHATWG spec](https://dom.spec.whatwg.org/#interface-attr).

```WebIDL
[Exposed=Window]
interface Attr

 : Node {
  readonly attribute DOMString? namespaceURI;
  readonly attribute DOMString? prefix;
  readonly attribute DOMString localName;
  readonly attribute DOMString name;
  [CEReactions] attribute DOMString value;

  readonly attribute Element? ownerElement;

  readonly attribute boolean specified; // useless; always returns true
};
```
