### ISSUE TITLE
WorkerGlobalScope has no performance property

### ISSUE THREAD

**Issue by chrisguttandin** [Microsoft/TSJS-lib-generator#163]
I'm not sure if that's the right place to raise that issue. Please tell me where else to post it when I'm wrong here.

I discovered that when specifying the lib "webworker" in a tsconfig file the performance property seems to be missing. According to [MDN](https://developer.mozilla.org/en-US/docs/Web/API/WorkerGlobalScope/performance) and a quick test in Chrome it is part of the WorkerGlobalScope. Shouldn't it be then also part of the "webworker" lib?

I'm new to TypeScript so there is a good chance I misunderstood something completely.

**Comment by mhegazy** [comment]
looks like a bug. PRs welcomed.

**Comment by rotemdan** [comment]
This [seems to have been fixed](https://github.com/Microsoft/TSJS-lib-generator/blame/master/baselines/webworker.generated.d.ts#L1407) in #186. I can verify the property exists for the worker scope in the latest TS nightly build.

**Comment by mhegazy** [comment]
thanks! closing
