### ISSUE TITLE
Error in definition of interface IteratorResult

### ISSUE THREAD

**Issue by lord-saumagen** [Microsoft/TSJS-lib-generator#172]
TypeScript Version: 2.0.6

Dear Ladies and Gentlemen,

I would like to bring to your attention, that the following interface is not conform to the specification in the "lib.es6.d.ts".

Currently defined as:

interface IteratorResult&lt;T&gt; {
    done: boolean;
    value: T;
}

The specification tells that the last IteratorResult returned form an iterator has the following values assigned:

done = true;
value = undefined,

So the correct interface definition would be:

interface IteratorResult&lt;T&gt; {
    done: boolean;
    value: T | undefined;
}

[See the description ad MDN: ](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/yield)

![mdn_yield](https://cloud.githubusercontent.com/assets/9468599/20868608/d802906a-ba5f-11e6-8dde-5a84d404d5ef.png)

Kind regards,

Lord Saumagen.

**Comment by SaschaNaz** [comment]
This should be on TS repo because [the definition is there](https://github.com/Microsoft/TypeScript/blob/0e74053abca1f6dd3671462b92f75c28c1430e81/src/lib/es2015.iterable.d.ts#L11)

**Comment by lord-saumagen** [comment]
Hello SaschaNaz,

thank you for your response. Unfortunately your recommendation is exactly the opposite of an earlier recommendation. See the image below.

![image](https://cloud.githubusercontent.com/assets/9468599/26162526/7a3d681e-3b16-11e7-818f-19db75b96d30.png)

That leads to the following question:

"Is there some kind of guideline which tells where to place issues to specific topics or is it just some kind of joke you randomly play with people who ask to many questions?"

However, I'm happy and grateful that at last somebody became aware of this issue. 

Kind regards, Lord Saumagen.

**Comment by SaschaNaz** [comment]
I think @zhengbli thought IteratorResult was on dom.generated.d.ts. Generally the guide is correct, but when the definition is not on `*.generated.d.ts` file it should be fixed on TS repo because TSJS-lib-generator cannot affect it.

This document may help: https://github.com/Microsoft/TypeScript/blob/master/src/lib/README.md

![image](https://cloud.githubusercontent.com/assets/3396686/26164951/4bd1d8ea-3b69-11e7-823d-ac1cd8e26b88.png)

**Comment by lord-saumagen** [comment]
Hello SaschaNaz, 

thank you for the clarification of that misunderstanding. 
Please be so kind and tell me what I have to do next. Do I have to repost that issue on the **TypeScript** repository or is there already somebody involved to solve that issue?

Kind regards, Lord Saumagen.

**Comment by SaschaNaz** [comment]
I trying simple searching before my comment and I couldn't find a relevant issue. Please repost on TS repo and underline that the type is on es2015.iterable.d.ts so that no one say that you have to return here again :smile:

**Comment by lord-saumagen** [comment]
Hello Kagami Sascha Rosylight,

thank you very much for your kind support. I'm going to repost the issue on
the TypeScript repository instantly.

Kind regards, Lord Saumagen.
