### ISSUE TITLE
Not overriding type IDBKeyPath

### ISSUE THREAD

**Issue by bondz** [Microsoft/TSJS-lib-generator#209]
In trying to fix, Microsoft/TypeScript#14322,
Simply adding, 

```json
    {
        "kind": "typedef",
        "name": "IDBKeyPath",
        "type": "string | string[]"
    }
```
in `overridingTypes.json` should fix the problem, but when I do, the type isn't updated. The solution was to remove the type and then add it again, which seems less than ideal.

**Comment by SaschaNaz** [comment]
IDBKeyPath is removed on the spec, you may want to override .keypath member itself.
