### ISSUE TITLE
Investigate whether EventTarget should be constructable

### ISSUE THREAD

**Issue by DanielRosenwasser** [Microsoft/TSJS-lib-generator#23]
It seems like it will always throw an error, so perhaps we shouldn't mark it as constructable.

**Comment by rielz** [comment]
Indeed. The DOM spec does not say it has a constructor:
[[WHATWG]](https://dom.spec.whatwg.org/#interface-eventtarget) [[W3C]](http://www.w3.org/TR/dom/#interface-eventtarget)

**Comment by zhengbli** [comment]
@mhegazy would removing the constructor affect the `typeof` operator on the interface?

**Comment by DanielRosenwasser** [comment]
As a type query, or a `typeof` expression?

As a type query on something of type `EventTarget`, you should see no difference.

If using a `typeof` expression, you'll get `"object"` back at runtime anyway.

So either way, there should be no difference.

**Comment by mhegazy** [comment]
i believe @zhengbli meant `instanceof` checks. an yes ti will be an error to call `x instanceof EventTarget`

**Comment by zhengbli** [comment]
@DanielRosenwasser @mhegazy sorry I meant `instanceof` check.

**Comment by rielz** [comment]
It would be sufficient to only remove the constructor (not the whole declared var).
EventTarget and its prototype property do exist in the global namespace.

**Comment by mhegazy** [comment]
the constructor does exist at runtime too, it is just illigal to call. This is the same for almost all DOM classes. i think the right fix here is to switch all DOM declarations to classes, and make thier constructors private. this requires https://github.com/Microsoft/TypeScript/issues/2341

**Comment by zhengbli** [comment]
As this issue belongs to a larger parent issue, I'm closing this one.
