### ISSUE TITLE
webspeechapi: Fix event types in `SpeechSynthesisUtterance`

### ISSUE THREAD

**Issue by andy-ms** [Microsoft/TSJS-lib-generator#232]
The [DefinitelyTyped](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/webspeechapi/index.d.ts) definitions for this API have some differences that appear correct. `SpeechSynthesisUtterance.onstart` and other methods should have a `SpeechSynthesisEvent` as their event type, and not just `Event`. We already have a `SpeechSynthesisEvent` type defined in `lib.dom.d.ts`, but aren't using it everywhere we should.

**Comment by saschanaz** [comment]
Fixed by #526
