### ISSUE TITLE
WebRTC types are lacking

### ISSUE THREAD

**Issue by andy-ms** [Microsoft/TSJS-lib-generator#233]
The type definitions on [DefinitelyTyped](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/13496b9ac261e398d0407c37463a1187b9cb539c/types/webrtc/RTCPeerConnection.d.ts) appear to get some things right that we don't.

* [RTCSdpType](https://www.w3.org/TR/webrtc/#idl-def-rtcsdptype): Should include "rollback"
* [RTCSessionDescription](https://www.w3.org/TR/webrtc/#idl-def-rtcsessiondescription): Properties should be readonly
* [RTCSessionDescriptionInit](https://www.w3.org/TR/webrtc/#idl-def-rtcsessiondescriptioninit): `type` should be required
* [RTCIceCandidate](https://www.w3.org/TR/webrtc/#idl-def-rtcicecandidate):
	- properties should be readonly
	- sdpMid and spdMLineIndex should be optional
* [RTCIceTransportPolicy](https://www.w3.org/TR/webrtc/#idl-def-rtcicetransportpolicy): Shouldn't include "none"
* [RTCIceTransportState](https://www.w3.org/TR/webrtc/#dom-rtcicetransportstate): Should include "failed"
* [RTCDtlsTransportState](https://www.w3.org/TR/webrtc/#dom-rtcdtlstransportstate): Should include "failed"
* [RTCRtpEncodingParameters](https://www.w3.org/TR/webrtc/#idl-def-rtcrtpencodingparameters): "maxFramerate" should be required
* [RTCPeerConnection.canTrickleIceCandidates](https://www.w3.org/TR/webrtc/#idl-def-rtcpeerconnection): should be optional (| undefined)
* [RTCPeerConnection](https://www.w3.org/TR/webrtc/#idl-def-rtcpeerconnection):
  - `configuration` should be optional
  - On the static side: Should have `defaultIceServers` and `generateCertificate`

Also, many of these RTC* types are in `lib.es6.d.ts`, but should probably be in `lib.dom.d.ts`.

**Comment by saschanaz** [comment]
Check out https://github.com/Microsoft/TSJS-lib-generator/pull/424 which fixes this, except `maxFramerate` and `configuration` things (because the spec has been changed).
