### ISSUE TITLE
Missing `error` event

### ISSUE THREAD

**Issue by falsandtru** [Microsoft/TSJS-lib-generator#261]
Window's `error` event should come from https://github.com/Microsoft/TSJS-lib-generator/blob/master/inputfiles/browser.webidl.xml#L12798, but it is missing with the generated .d.ts file.

https://github.com/Microsoft/TSJS-lib-generator/blob/master/baselines/dom.generated.d.ts#L13045

@zhengbli Can you take a look?

cc @SaschaNaz for your pr.

**Comment by falsandtru** [comment]
Ah, now TS.fsx is maintained by @mhegazy as the only committer? Can you take a look instead of him?

**Comment by SaschaNaz** [comment]
This is because the `onerror` event property has a special handler named ErrorEventHandler instead of normal EventHandler. TS.fsx (incorrectly) checks for EventHandler thus the `error` event is omitted.

**Comment by falsandtru** [comment]
Thanks for letting me know!

**Comment by SaschaNaz** [comment]
It seems `touch*` events on `Window` interface are also affected.

**Comment by thw0rted** [comment]
Is there a reason why the generated `GlobalEventHandlers` entries all look like

        ondurationchange: ((this: GlobalEventHandlers, ev: Event) => any) | null;

except for `onerror`, which is just `ErrorEventHandler`, without allowing for `null`?  Is it actually not legal to un-register the error handler by setting `window.onerror = null`?

If this is incorrect, should I open a separate issue to fix it?

**Comment by saschanaz** [comment]
>should I open a separate issue to fix it?

@thw0rted Yes, please do.
