### ISSUE TITLE
window is missing Intersection Observer API

### ISSUE THREAD

**Issue by OliverJAsh** [Microsoft/TSJS-lib-generator#266]
Example:

``` ts
new IntersectionObserver(() => {}); // no error
window.IntersectionObserver // error: Property 'IntersectionObserver' does not exist on type 'Window'.
```

Related issue: https://github.com/Microsoft/TypeScript/issues/16255

If I wanted to raise a PR to fix this, am I right in thinking that I need to add a property to the `Window` interface in [`addedTypes.json`](https://github.com/Microsoft/TSJS-lib-generator/blob/c55727b5ed46040dd079c52af716bcd7fd05eaf3/inputfiles/addedTypes.json#L229)?

**Comment by mhegazy** [comment]
added by https://github.com/Microsoft/TSJS-lib-generator/pull/270
