### ISSUE TITLE
DOM's Fetch Response interface is missing the `redirected` attribute

### ISSUE THREAD

**Issue by chaucerbao** [Microsoft/TSJS-lib-generator#274]
The DOM lib definitions for the Fetch API seems to be missing the [redirected attribute](https://fetch.spec.whatwg.org/#dom-response-redirected) (boolean) in the [Response interface](https://fetch.spec.whatwg.org/#response-class).

**Comment by arjunyel** [comment]
Fixed with https://github.com/Microsoft/TSJS-lib-generator/pull/280
