### ISSUE TITLE
Typo in MediaTrackConstraintSet

### ISSUE THREAD

**Issue by sk-** [Microsoft/TSJS-lib-generator#285]
Instead of `echoCancelation` the field should be called `echoCancellation` as per the spec https://w3c.github.io/mediacapture-main/getusermedia.html#media-track-constraints

**Comment by mhegazy** [comment]
A PR would be appreciated.

**Comment by chris-morgan** [comment]
Duplicate of #251.

**Comment by saschanaz** [comment]
This is fixed now.
