### ISSUE TITLE
Fetch headers as object literal?

### ISSUE THREAD

**Issue by andy-ms** [Microsoft/TSJS-lib-generator#289]
Our definition of `RequestInit` includes:
```ts
headers?: Headers | string[][]
```

From [mdn](https://developer.mozilla.org/en-US/docs/Web/API/WindowOrWorkerGlobalScope/fetch), the headers should be "a Headers object or an object literal with ByteString values". The [isomorphic-fetch](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/cb2dbfbb50afbff23de701e8d630f5cfde57832e/types/isomorphic-fetch/isomorphic-fetch-tests.ts) tests are now failing; they try to use `fetch` like:
```ts
fetch("http://my.url.com", { headers: { 'Content-Type': 'application/json' } });
```

This indicates that the second option should be `{ [key: string]: string }`, not `string[][]`.
In TypeScript `2.4` we simply had `headers?: any;`, so the test failures are new.

There are also failing tests for [`chocolatechipjs`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/cb2dbfbb50afbff23de701e8d630f5cfde57832e/types/chocolatechipjs/chocolatechipjs-tests.ts).

**Comment by SaschaNaz** [comment]
It should be `headers: HeadersInit`, with `typedef HeadersInit = string[][] | { [key: string]: string }`. https://fetch.spec.whatwg.org/#typedefdef-headersinit

**Comment by timocov** [comment]
Related to Microsoft/TypeScript#19656

**Comment by timocov** [comment]
I have a little patch to fix this, but seems that overrides does not work. @andy-ms do you know why overrides with `"name": "headers?"` in `overridingTypes.json` does not work correctly? If I remove `?` from name overrides is applied but in this case definitions is wrong.

Also I think that `[string, string][]` is more correct that `string[][]` but it is not by specs - what do you think?

```patch
diff --git a/inputfiles/addedTypes.json b/inputfiles/addedTypes.json
index dec2389..1302c15 100644
--- a/inputfiles/addedTypes.json
+++ b/inputfiles/addedTypes.json
@@ -1794,5 +1794,10 @@
         "signatures": [
             "reportValidity(): boolean"
         ]
+    },
+    {
+        "kind": "typedef",
+        "name": "HeadersInit",
+        "type": "[string, string][] | { [key: string]: string }"
     }
 ]
diff --git a/inputfiles/overridingTypes.json b/inputfiles/overridingTypes.json
index c1236aa..85888a9 100644
--- a/inputfiles/overridingTypes.json
+++ b/inputfiles/overridingTypes.json
@@ -1381,7 +1381,7 @@
         "kind": "constructor",
         "interface": "Headers",
         "signatures": [
-            "new(init?: Headers | string[][] | object): Headers"
+            "new(init?: HeadersInit): Headers"
         ]
     },
     {
@@ -1389,5 +1389,17 @@
         "interface": "ServiceWorkerContainer",
         "name": "getRegistration",
         "signatures": ["getRegistration(): Promise<ServiceWorkerRegistration | undefined>"]
+    },
+    {
+        "kind": "property",
+        "interface": "RequestInit",
+        "name": "headers?",
+        "type": "HeadersInit"
+    },
+    {
+        "kind": "property",
+        "interface": "ResponseInit",
+        "name": "headers?",
+        "type": "HeadersInit"
     }
  ]
diff --git a/inputfiles/removedTypes.json b/inputfiles/removedTypes.json
index 9168ace..cfe4768 100644
--- a/inputfiles/removedTypes.json
+++ b/inputfiles/removedTypes.json
@@ -77,5 +77,9 @@
     {
         "kind": "typedef",
         "name": "JSON"
+    },
+    {
+        "kind": "typedef",
+        "name": "HeadersInit"
     }
 ]
```

**Comment by timocov** [comment]
Possible @mhegazy may helps too?

**Comment by mhegazy** [comment]
> I have a little patch to fix this, but seems that overrides does not work. @andy-ms do you know why overrides with "name": "headers?" in overridingTypes.json does not work correctly? If I remove ? from name "headers?" overrides is applied but in this case definitions is wrong.

if you can share the PR i can look into it.

> Also I think that [string, string][] is more correct that string[][] but it is not by specs - what do you think?

The spec does not say anything about it being a tuple, possible cause the webidl does not have these, but it is not clear why it is `[string, string][]` and `string[][]`

>  typedef (sequence<sequence<ByteString>> or record<ByteString, ByteString>) HeadersInit;

**Comment by timocov** [comment]
> The spec does not say anything about it being a tuple, possible cause the webidl does not have these, but it is not clear why it is [string, string][] and string[][]

Ok

> if you can share the PR i can look into it.

Please take a look at #315
