### ISSUE TITLE
// @ts-check doesn't know Web Bluetooth and Generic Sensors

### ISSUE THREAD

**Issue by mjbvz** [Microsoft/TSJS-lib-generator#294]
_From @kenchris on September 14, 2017 13:25_

I get errors for navigator.bluetooth Accelerometer, Magnetometer etc.

If you can tell me where this can be added and how to, we can supply PRs

_Copied from original issue: Microsoft/vscode#34376_

**Comment by mhegazy** [comment]
closing in favor of https://github.com/Microsoft/TypeScript/issues/18482 and https://github.com/Microsoft/TypeScript/issues/18481
