### ISSUE TITLE
// @ts-check complains about screen.orientation and suggest msOrientation

### ISSUE THREAD

**Issue by mjbvz** [Microsoft/TSJS-lib-generator#295]
_From @kenchris on September 14, 2017 13:42_

```[js] Property 'orientation' does not exist on type 'Screen'. Did you mean 'msOrientation'?```

Though screen.orientation is what Chrome uses

```  mat4.rotateZ(this.rotationMatrix, this.rotationMatrix, toRad(window.screen.orientation.angle || 0));```

_Copied from original issue: Microsoft/vscode#34381_

**Comment by mhegazy** [comment]
Documentation: https://developer.mozilla.org/en-US/docs/Web/API/Screen/orientation.

**Comment by mhegazy** [comment]
PRs welcomed. You can find more information about contributing lib.d.ts fixes at https://github.com/Microsoft/TypeScript/blob/master/CONTRIBUTING.md#contributing-libdts-fixes.

**Comment by mhegazy** [comment]
closing in favor of https://github.com/Microsoft/TypeScript/issues/18480
