### ISSUE TITLE
new URL() constructor does not take URL object as base parameter

### ISSUE THREAD

**Issue by Nullizer** [Microsoft/TSJS-lib-generator#331]
[https://url.spec.whatwg.org/#example-5434421b](https://url.spec.whatwg.org/#example-5434421b)

> A URL object can be used as base URL (while IDL requires a string as argument, a URL object stringifies to its href attribute value):
`var url = new URL("🏳️‍🌈", new URL("https://pride.example/hello-world"))`

Now it's only support DOMString as base parameter, need explicit call toString method on base to avoid compile error.
![default](https://user-images.githubusercontent.com/4851833/33204115-68e08822-d13d-11e7-8973-8d9d9fde8bb1.png)
Related: Microsoft/TypeScript#15246

**Comment by Nullizer** [comment]
I made a PR for this #332

**Comment by saschanaz** [comment]
Ideally we should support interfaces with stringifiers, not sure how.
