### ISSUE TITLE
DOM is missing focusin and focusout

### ISSUE THREAD

**Issue by tkrotoff** [microsoft/TSJS-lib-generator#333]
See https://github.com/Microsoft/TSJS-lib-generator/blob/42ec97fcb7ed0166220a7b524fa0a056dbbb819a/baselines/dom.generated.d.ts#L2550
See https://developer.mozilla.org/en-US/docs/Web/Events/focusin
See https://developer.mozilla.org/en-US/docs/Web/Events/focusout

**Comment by mhegazy** [comment]
PRs welcomed. You can find more information about contributing lib.d.ts fixes at https://github.com/Microsoft/TypeScript/blob/master/CONTRIBUTING.md#contributing-libdts-fixes.

**Comment by saschanaz** [comment]
Fixed by #696
