### ISSUE TITLE
DOM legacy event properties (onclick, onload, etc) should be nullable

### ISSUE THREAD

**Issue by Kovensky** [Microsoft/TSJS-lib-generator#334]
Currently, `HTMLElement` (and other elements') event handlers are specified as function types only, but they are actually supposed to be `null`able. This prevents old-style event handlers from being unset under `--strictNullChecks` without weird things such as assigning to `null!` (a value of type `never`).

Quoth https://html.spec.whatwg.org/multipage/webappapis.html#event-handler-attributes:

"An event handler has a value, which is either `null`, or is a callback object, or is an internal raw uncompiled handler. The `EventHandler` callback function type describes how this is exposed to scripts. Initially, an event handler's value must be set to `null`."

"`null` or callback" is the only part that is relevant to JS/TS itself.

**Comment by saschanaz** [comment]
This has been fixed 🤔

**Comment by saschanaz** [comment]
This has been fixed 🎉
