### ISSUE TITLE
NotificationOptions missing many attributes

### ISSUE THREAD

**Issue by ialexryan** [Microsoft/TSJS-lib-generator#335]
Hi there! Per @mhegazy in https://github.com/Microsoft/TypeScript/issues/3111, creating a new issue.

In https://github.com/Microsoft/TSJS-lib-generator/blob/master/baselines/dom.generated.d.ts#L670-L676, you can see that only `body`, `dir`, `icon`, `lang`, and `tag` are defined. But there are plenty more, including `actions`, `vibrate`, `image`, etc.

(If added there, they may also need to be added here: https://github.com/Microsoft/TSJS-lib-generator/blob/master/baselines/dom.generated.d.ts#L8552)

If you're curious, [the original comment](https://github.com/Microsoft/TypeScript/issues/3111#issuecomment-269299030) from @marcovdb contained the full list of fifteen. I'm not sure why @zhengbli only chose to merge these five.

**Comment by saschanaz** [comment]
#438 fixed this 🎉

**Comment by ialexryan** [comment]
It totally did, woo!

https://github.com/Microsoft/TSJS-lib-generator/blob/master/baselines/dom.generated.d.ts#L1031-L1046
