### ISSUE TITLE
[documentation] Where is JS.fs?

### ISSUE THREAD

**Issue by qm3ster** [Microsoft/TSJS-lib-generator#336]
It appears JS.fs and the domWeb.js and domWindows.js are long gone.
https://github.com/Microsoft/TSJS-lib-generator/blob/master/README.md#code-structure should be changed to reflect that or removed.

**Comment by mhegazy** [comment]
A PR would be appreciated.

**Comment by qm3ster** [comment]
If you meant me, I'm not familiar with F# or this project, I just contributed typedefs.

**Comment by saschanaz** [comment]
Just removing the JS.fs line from README should be good enough.

**Comment by qm3ster** [comment]
Please take a look at #339 
The following sentence concerns me:
>There are three json files that are used to alter the file generation: `addedTypes.json`, `overridingTypes.json`, and `removedTypes.json`.

These are not the only ones. So do:
- `comments.json`: they don't affect the types, but they do affect editor tooltips for instance, and the test.
- `knownWorker{Enums|Interfaces}.json`: These actually affect typechecking in the webworker context.
As far as I understand, people are welcome to contribute to these as well.

Also, should `sample.json` have a `**Do not edit this file**.`?

**Comment by saschanaz** [comment]
sample.json shouldn't change unless the format of browser.input.xml changes, so yes it should.

I agree for comments and knownWorker files.

**Comment by qm3ster** [comment]
So, "there are six files affecting"? This just duplicates the list at the end. What to put?

**Comment by saschanaz** [comment]
I think it's better to replace *alter the file generation* with *alter types*, as I think that is what the sentence really wants to say.

**Comment by qm3ster** [comment]
`knownWorker{Enums|Interfaces}.json` changes types in `webworker.generated.d.ts`

**Comment by saschanaz** [comment]
I would say that it changes type exposure configuration (similar to what `[Exposed=Worker]` does in Web IDL), but a global web type itself does not change. It depends on how we say, though...

**Comment by qm3ster** [comment]
#339 I think it's done.
