### ISSUE TITLE
IDBKeyPath also supports string[]

### ISSUE THREAD

**Issue by wkrueger** [Microsoft/TSJS-lib-generator#346]
In lib.es2017.full.d.ts
```
type IDBKeyPath = string;
```
expected
```
type IDBKeyPath = string | string[];
```
according to https://developer.mozilla.org/en-US/docs/Web/API/IDBDatabase/createObjectStore

**Comment by saschanaz** [comment]
IDBKeyPath is not in the spec, instead `IDBObjectStoreParameters` now has `keyPath?: string | string[];`.
