### ISSUE TITLE
Code duplication

### ISSUE THREAD

**Issue by shvabuk** [Microsoft/TSJS-lib-generator#347]
**TypeScript Version:**  2.6.2
Code duplication in files:

> Duplication in file: lib.d.ts on lines: 4862 & 18427
> Duplication in file: lib.dom.d.ts on lines: 776 & 14341
> Duplication in file: lib.es2016.full.d.ts on lines: 779 & 14344
> Duplication in file: lib.es2017.full.d.ts on lines: 783 & 14348
> Duplication in file: lib.es6.d.ts on lines: 6549 & 20114
> Duplication in file: lib.esnext.full.d.ts on lines: 780 & 14345
> Duplication in file: lib.webworker.d.ts on lines: 1882 & 1900

**Actual:**
https://github.com/Microsoft/TypeScript/blob/master/lib/lib.webworker.d.ts#L1882
https://github.com/Microsoft/TypeScript/blob/master/lib/lib.webworker.d.ts#L1900

According to https://github.com/Microsoft/TypeScript/issues/20473

searchDuplicates script: https://gist.github.com/shvabuk/ad6b9974794dc7595c5832722df443fa

**Comment by mhegazy** [comment]
These files are not meant to be used together.  currently the compiler if no `--lib` is specified, it needs a single library file to include. 

https://github.com/Microsoft/TypeScript/pull/15780 will allow us to split these files and add references to them instead of having to duplicate the code.
