### ISSUE TITLE
Wrong signature for WebKitEntriesCallback/WebKitErrorCallback/WebKitFileCallback

### ISSUE THREAD

**Issue by 6r1anchen** [Microsoft/TSJS-lib-generator#351]
I was trying to override callback interface signature for `WebKitEntriesCallback`/`WebKitErrorCallback`/`WebKitFileCallback`, added below `json` in `overridingTypes.json`:
```
    {
        "kind": "callback",
        "interface": "WebKitEntriesCallback",
        "signatures": [
            "(entities: WebKitEntry[]): void"
        ]
    },
    {
        "kind": "callback",
        "interface": "WebKitErrorCallback",
        "signatures": [
            "(err: DOMError): void"
        ]
    },
    {
        "kind": "callback",
        "interface": "WebKitFileCallback",
        "signatures": [
            "(file: File): void"
        ]
    }
```
based on [.file()](https://developer.mozilla.org/en-US/docs/Web/API/FileSystemFileEntry/file) and [.readEntries()](https://developer.mozilla.org/en-US/docs/Web/API/FileSystemDirectoryReader/readEntries). Related Typescript repo issue [#18139](https://github.com/Microsoft/TypeScript/issues/18139)

Then I changed `baselines/dom.generated.d.ts` to:
```
interface WebKitEntriesCallback {
    (entries: WebKitEntry[]): void;
}

interface WebKitErrorCallback {
    (err: DOMError): void;
}

interface WebKitFileCallback {
    (file: File): void;
}
```
But when I run `./build` to build and test, `dom.generated.d.ts` is still the same, the snapshot test for it failed.
I am not familiar with F# here, is my `json` input wrong in this case, or it is a bug from the build script?

eg: in `browser.webidl.xml`, these callbacks defined as:
```
  <callback-interfaces>
    ...
    <interface name="WebKitEntriesCallback" extends="Object">
      <methods>
        <method name="handleEvent" type="void">
          <param name="entries" type="WebKitEntry[]"/>
        </method>
      </methods>
    </interface>
    <interface name="WebKitErrorCallback" extends="Object">
      <methods>
        <method name="handleEvent" type="void">
          <param name="err" type="DOMError"/>
        </method>
      </methods>
    </interface>
    <interface name="WebKitFileCallback" extends="Object">
      <methods>
        <method name="handleEvent" type="void">
          <param name="file" type="File"/>
        </method>
      </methods>
    </interface>
  </callback-interfaces>
```

**Comment by saschanaz** [comment]
You should use `"name"` instead of `"interface"`. Take a look at this example:

https://github.com/Microsoft/TSJS-lib-generator/blob/945e4c558f615f534457ec5807e884e49164184b/inputfiles/overridingTypes.json#L502-L508

**Comment by 6r1anchen** [comment]
@saschanaz Thanks for your input,
I changed it to:
```
    {
        "kind": "callback",
        "name": "WebKitEntriesCallback",
        "signatures": [
            "(entities: WebKitEntry[]): void"
        ]
    },
    {
        "kind": "callback",
        "name": "WebKitErrorCallback",
        "signatures": [
            "(err: DOMError): void"
        ]
    },
    {
        "kind": "callback",
        "name": "WebKitFileCallback",
        "signatures": [
            "(file: File): void"
        ]
    }
```
but the output `dom.generated.d.ts`, is still the same, no luck.
I suspect more it is caused by parsing from:
```
  <callback-interfaces>
    <interface name="EventListener" extends="Object">
      <methods>
        <method name="handleEvent" type="void">
          <param name="evt" type="Event"/>
        </method>
      </methods>
    </interface>
    <interface name="WebKitEntriesCallback" extends="Object">
      <methods>
        <method name="handleEvent" type="void">
          <param name="entries" type="WebKitEntry[]"/>
        </method>
      </methods>
    </interface>
    <interface name="WebKitErrorCallback" extends="Object">
      <methods>
        <method name="handleEvent" type="void">
          <param name="err" type="DOMError"/>
        </method>
      </methods>
    </interface>
    <interface name="WebKitFileCallback" extends="Object">
      <methods>
        <method name="handleEvent" type="void">
          <param name="file" type="File"/>
        </method>
      </methods>
    </interface>
  </callback-interfaces>
```
to `.d.ts`, since `xml` indicate that interface `WebKitEntriesCallback` should be more like:
```
interface WebKitEntriesCallback {
    handleEvent(entries: WebKitEntry[]): void;
}
```
but current output is
```
interface WebKitEntriesCallback {
        (evt: Event): void;
}
```
which is more like `EventListener` signature.

**Comment by saschanaz** [comment]
Ah, my bad, I thought WebKitEntriesCallback was a callback function, but it is a callback interface.

The current build script does not support overriding a callback interface:

https://github.com/Microsoft/TSJS-lib-generator/blob/048c8bd0c2d47b5c234f47a4490b2e236d11688b/TS.fsx#L858-L862

So you should modify the F# script first to fix this problem.

**Comment by saschanaz** [comment]
(BTW, I think lib.d.ts should ultimately exclude all those WebKit-specific types and require third-party definition files)

**Comment by saschanaz** [comment]
Fortunately I got a fix from my old unmerged PR and opened a new one: #352

**Comment by 6r1anchen** [comment]
@saschanaz Nice 👍  Thanks for your help
