### ISSUE TITLE
Allow the trailing newline

### ISSUE THREAD

**Issue by falsandtru** [Microsoft/TSJS-lib-generator#37]
Please allow the trailing newline in tests. GitHub editor on browser add the trailing newline.

**Comment by zhengbli** [comment]
What newlines are you referring to? The CI tests are all tests used in TypeScript repo, and the one additional test we do is comparing the generated files with the baselines, which you wouldn't be editing directly.

**Comment by falsandtru** [comment]
These comparing target files:
https://github.com/Microsoft/TSJS-lib-generator/blob/master/build.fsx#L16-L22

When I added the trailing newline to https://github.com/Microsoft/TSJS-lib-generator/blob/master/baselines/dom.generated.d.ts, it test was failed.

https://ci.appveyor.com/project/zhengbli/tsjs-lib-generator/build/1.0.58-ihgxbkbv
https://ci.appveyor.com/project/zhengbli/tsjs-lib-generator/build/1.0.58-xmmtfrin

**Comment by zhengbli** [comment]
I don't think there would be much gain from treating the trailing newline specially. The working flow is designed to be the case that the baseline files are copied from generated new files, instead of being updated manually. That way the new baseline files are guaranteed to tested.

**Comment by falsandtru** [comment]
I see, thanks for your explaination.
