### ISSUE TITLE
Use an interface for `AnimationKeyFrame`

### ISSUE THREAD

**Issue by andy-ms** [Microsoft/TSJS-lib-generator#377]
It's currently not possible to write `web-animations-js` on DefinitelyTyped to be both backward-compatible and not conflict with the current definition of `AnimationKeyFrame`. For some reason it is currently declared as:
```ts
type AnimationKeyFrame = {offset?: number | null | (number | null)[]} & {[key: string]: string | number | number[] | string[]};
```
, where if it were declared as an interface it would not conflict with the definition in `web-animations-js`.

**Comment by mhegazy** [comment]
Thought the definition we had was more accurate, I have changed it to an interface for now.

**Comment by andy-ms** [comment]
Apparently this still isn't possible because we can't write a string index signature twice. (DefinitelyTyped/DefinitelyTyped#23793)
```ts
interface I {
    [s: string]: any;
}
interface I {
    [s: string]: any; // Error
}
```
