### ISSUE TITLE
clearTimeout and clearInterval could accept undefined

### ISSUE THREAD

**Issue by denis-sokolov** [Microsoft/TSJS-lib-generator#379]
_I suspect this issue is in a wrong place. Forgive me if I missed where I can raise it for it to be more appropriate._

`clearTimeout` and `clearInterval` are [currently typed](https://github.com/Microsoft/TSJS-lib-generator/blob/b60e68d7f18d9158d8ea84b4e25320a4d147bfde/baselines/webworker.generated.d.ts#L1522) as `(handle: number) => void`. I’d like that to change to accept `undefined`: `(handle?: number) => void)`. 

The [WHATWG spec says](https://html.spec.whatwg.org/multipage/timers-and-user-prompts.html#dom-cleartimeout) anything goes as a handle:

> If handle does not identify an entry in the list of active timers of the WindowOrWorkerGlobalScope object on which the method was invoked, the method does nothing.

In practice passing in an obviously invalid value (like `Hello`) is an error we’d like to catch, but passing in `undefined` is a common enough event:

```ts
let myTimer;

sometimeInTheFuture(function(){
  myTimer = window.setTimeout(...);
});

sometimeInTheFuture(function(){
  window.clearTimeout(myTimer);
});
```

Obviously the latter can be guarded with a conditional, but in practice, given that browsers ignore `clearTimeout` with `undefined`, an unguarded version is used in many codebases I have seen.

**Comment by HolgerJeromin** [comment]
Some programmers use `myTimer: number | null`.

**Comment by saschanaz** [comment]
This has been fixed 🎉
