### ISSUE TITLE
Add the decoding property to Image

### ISSUE THREAD

**Issue by fathyb** [Microsoft/TSJS-lib-generator#392]
`Image.decoding` isn't present on the DOM typings.

I can't find the spec, but it's mentioned on different places :
- [WHATWG PR](https://github.com/whatwg/html/pull/3221)
- [on MDN, but you have to scroll or search for "decoding"](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/img)
- [Chromium's Intent to Ship](https://groups.google.com/a/chromium.org/forum/#!topic/Blink-dev/MbXp16hQclY) (they say Edge supports it, isn't TypeScript lib from Edge's IDL?)
- [Chromium IDL](https://chromium.googlesource.com/chromium/src/+/master/third_party/WebKit/Source/core/html/HTMLImageElement.idl#43)

**Comment by mhegazy** [comment]
PRs welcomed. You can find more information about contributing lib.d.ts fixes at https://github.com/Microsoft/TypeScript/blob/master/CONTRIBUTING.md#contributing-libdts-fixes.
