### ISSUE TITLE
Performance interface returns any instead of actual types

### ISSUE THREAD

**Issue by JoshuaKGoldberg** [Microsoft/TSJS-lib-generator#395]
https://developer.mozilla.org/en-US/docs/Web/API/Performance

For example, `getEntries(): any;` should be `getEntries(): PerformanceEntry`

**Comment by mhegazy** [comment]
PRs welcomed. You can find more information about contributing lib.d.ts fixes at https://github.com/Microsoft/TypeScript/blob/master/CONTRIBUTING.md#contributing-libdts-fixes.

**Comment by a-tarasyuk** [comment]
@mhegazy @JoshuaKGoldberg 

Based on spec `getEntries()`([Performance `interface`](https://www.w3.org/TR/performance-timeline/#extensions-to-the-performance-interface)) returns `PerformanceEntryList` (`type PerformanceEntry[]`, [Changes](https://github.com/a-tarasyuk/TSJS-lib-generator/commit/418bc7cb4df94183a5257127ba7bdc1889f7a699)), however, browsers can return more specific types([`getEntries` spec](https://developer.mozilla.org/en-US/docs/Web/API/Performance/getEntries)) which were inherited from `PerformanceEntry`, like so

Chrome: `getEntries()`:
```shell
[PerformanceNavigationTiming, PerformanceResourceTiming, PerformancePaintTiming ...]
```

FF: `getEntries()`
```shell
[ PerformanceNavigationTiming, PerformanceResourceTiming, ...]
```
