### ISSUE TITLE
Revert #409?

### ISSUE THREAD

**Issue by saschanaz** [Microsoft/TSJS-lib-generator#419]
```webidl
  AudioParam setValueCurveAtTime (sequence<float> values, double startTime, double duration);
```

```webidl
dictionary WaveShaperOptions : AudioNodeOptions {
  sequence<float> curve;
  OverSampleType oversample = "none";
};
```

@iccir suggested in #408 that we should use Float32Array citing [an older spec](https://www.w3.org/TR/webaudio/#widl-AudioParam-setValueCurveAtTime-AudioParam-Float32Array-values-double-startTime-double-duration), but [the latest one says it's `sequence<float>`](https://webaudio.github.io/web-audio-api/#AudioParam).

#409 also changed `VRLayer` and [it also has `sequence<float>`](https://immersive-web.github.io/webvr/spec/1.1/#interface-vrlayerinit). (It's now `VRLayerInit`.)

So I suggest that we revert #409, what do you think? @mhegazy

**Comment by saschanaz** [comment]
Sequences cannot be used for attributes, so it may make sense.

**Comment by mhegazy** [comment]
@saschanaz what about the other APIs that changed?

Maybe the right fix is to revert the change and add a specific override for setValueCurveAtTime. 

Sorry for making the changes without checking the updated spec

**Comment by saschanaz** [comment]
I think that's all.

Full diff:

```diff
--- a/baselines/dom.generated.d.ts
+++ b/baselines/dom.generated.d.ts
@@ -1033,8 +1033,8 @@ interface PeriodicWaveConstraints {
 }

 interface PeriodicWaveOptions extends PeriodicWaveConstraints {
-    imag?: Float32Array;
-    real?: Float32Array;
+    imag?: number[];
+    real?: number[];
 }

 interface PointerEventInit extends MouseEventInit {
@@ -1569,8 +1569,8 @@ interface VRDisplayEventInit extends EventInit {
 }

 interface VRLayer {
-    leftBounds?: Float32Array | null;
-    rightBounds?: Float32Array | null;
+    leftBounds?: number[] | null;
+    rightBounds?: number[] | null;
     source?: HTMLCanvasElement | null;
 }

@@ -1581,7 +1581,7 @@ interface VRStageParameters {
 }

 interface WaveShaperOptions extends AudioNodeOptions {
-    curve?: Float32Array;
+    curve?: number[];
     oversample?: OverSampleType;
 }

@@ -1984,7 +1984,7 @@ interface AudioParam {
     linearRampToValueAtTime(value: number, endTime: number): AudioParam;
     setTargetAtTime(target: number, startTime: number, timeConstant: number): AudioParam;
     setValueAtTime(value: number, startTime: number): AudioParam;
-    setValueCurveAtTime(values: Float32Array, startTime: number, duration: number): AudioParam;
+    setValueCurveAtTime(values: number[], startTime: number, duration: number): AudioParam;
 }

 declare var AudioParam: {
```

**Comment by iccir** [comment]
That reverts it, but the original issue remains: `setValueCurveAtTime` needs to be able to take a `Float32Array` without warning.

I'm also not sure what the official policy is regarding specifications that haven't been adopted by all browsers. [Firefox](https://bugzilla.mozilla.org/show_bug.cgi?id=1421091) and Safari both require Float32Array and throw an exception on other types.

**Comment by saschanaz** [comment]
Another general solution is creating new WebIDL-compatible `Sequence<T>` type.

[The spec says] iterable objects can be casted as IDL sequence type, so we may do:

```ts
type Sequence<T> = T[] | { [Symbol.iterator]: IterableIterator<T> };
```

I have no idea how to make this ES5-compatible though.

**Comment by mhegazy** [comment]
ES5 vs ES6 is the issue here..

**Comment by mhegazy** [comment]
So every use of `Sequence<float>` should be `number[] | Float32Array` ?

**Comment by saschanaz** [comment]
>So every use of Sequence<float> should be number[] | Float32Array ?

For now, yes.

>Looks like all the changes in #409 were in input positions

Actually it's guaranteed by the WIDL spec 😁

**Comment by iccir** [comment]
Is `number[] | Float32Array` too narrow? Isn't `sequence<float>` any object with a `length` that returns float-like values via its subscript operator? 

Chrome appears to accept Float64Array and Int16Array values for `setValueCurveAtTime()`, but I'm not sure if this is what the spec intended.

**Comment by saschanaz** [comment]
That's the intended behavior, but there is no good general way in TS to allow it. Explicitly allowing every possible interfaces will be too exhaustive.

**Comment by iccir** [comment]
Makes sense, thanks! `number[] | Float32Array` (and *maybe* Float64Array?) should cover most use cases.

**Comment by saschanaz** [comment]
ArrayBufferView may be the best option for those typed arrays.

**Comment by iccir** [comment]
`ArrayBufferView` includes `DataView`, which I believe isn't allowed in `sequence<float>` due to the lack of `[]` and `length`.
