### ISSUE TITLE
relList in HTMLAnchorElement

### ISSUE THREAD

**Issue by Connormiha** [Microsoft/TSJS-lib-generator#423]
**Search Terms:**
HTMLAnchorElement
dom

**Request:**
Add `relList` property in `HTMLAnchorElement`
https://developer.mozilla.org/en-US/docs/Web/API/HTMLAnchorElement/relList

**Comment by mhegazy** [comment]
PRs welcomed. you can look at https://github.com/Microsoft/TSJS-lib-generator/pull/402 as a guide for how to add a missing property.

**Comment by mhegazy** [comment]
Fixed by https://github.com/Microsoft/TSJS-lib-generator/pull/425
