### ISSUE TITLE
IDBValidKey does not exist in lib.webworker.d.ts

### ISSUE THREAD

**Issue by mmermerkaya** [Microsoft/TSJS-lib-generator#426]
This type exists in DOM types, but does not exist in Web Worker types. It should exist in both, as IndexedDB spec and implementation is the same for both.

It is defined [here](https://github.com/Microsoft/TSJS-lib-generator/blob/818f7457e6bffe0bd8255f4e00f1b1dd700cd425/inputfiles/addedTypes.json#L2876).

**Comment by mhegazy** [comment]
Types in worker file come from https://github.com/Microsoft/TSJS-lib-generator/blob/master/inputfiles/knownWorkerTypes.json. PRs welcomed adding the missing type.
