### ISSUE TITLE
MSManipulationEvent is missing

### ISSUE THREAD

**Issue by andy-ms** [Microsoft/TSJS-lib-generator#429]
This was present in `typescript@2.7` but is now missing. Same for `MSHTMLWebViewElement` and `MSRangeCollection`. This affects `blissfuljs` on DefinitelyTyped.

**Comment by mhegazy** [comment]
Some of these types were removed intentionally as they were MS-specific types. see https://github.com/Microsoft/TypeScript/wiki/Breaking-Changes#some-ms-specific-types-are-removed-from-libdts for the full list.

For the missing types, the libraries can copy the old declaration, and it should work.
