### ISSUE TITLE
URLSearchParams.set possibly invalid definition.

### ISSUE THREAD

**Issue by chyzwar** [Microsoft/TSJS-lib-generator#464]
URLSearchParams.set

```ts
set(name: string, value: string): void;
```

according to browsers behaviour:

```ts
set(name: string, value: any): void;
```

URLSearchParams.set will stringify value at least in Chrome and Firefox. But in spec signature suggest string only. [urlsearchparams](https://url.spec.whatwg.org/#interface-urlsearchparams)

Typescript should privide type definitions spec compliant or follow actual browser implementation?

**Comment by saschanaz** [comment]
True, as all string type arguments will automatically call stringifier to get strings. But:

```
var s = new URLSearchParams();
var u = new URL("http://example.com");
s.set("example", u);
console.log(s.get("example")); // "http://example.com", okay

s.set(u, "example");
console.log(s.get("http://example.com")); // "example". 🤔
```

Not only `value` but all Web IDL string arguments will automatically stringify things. So we should replace every `string` to `any`? Probably no...

**Comment by saschanaz** [comment]
Ideally we may allow types with `stringifier` but currently there is no way to do that.
