### ISSUE TITLE
Missing property in window.navigator: Property 'userLanguage' does not exist on type 'Navigator'.

### ISSUE THREAD

**Issue by AlexanderEllis** [Microsoft/TSJS-lib-generator#478]
When trying to access `window.navigator.userLanguage` to add language support for Internet Explorer users, I'm getting the following TS error:

`[ts] Property 'userLanguage' does not exist on type 'Navigator'.`

I see that [NavigatorLanguage](https://github.com/Microsoft/TSJS-lib-generator/blob/master/baselines/dom.generated.d.ts#L10226) has both `language` and `languages`, but not `userLanguage`.  

https://github.com/Microsoft/TSJS-lib-generator/blob/2c2403e09d28c58a72dcad08bd718288e30df2b3/baselines/dom.generated.d.ts#L10226-L10229

I believe `userLanguage` is specific to IE [(source 1)](https://msdn.microsoft.com/en-us/library/dn705466(v=vs.85).aspx)  [(source 2)](https://developer.mozilla.org/en-US/docs/Web/API/NavigatorLanguage/language#Browser_compatibility), and I'm not exactly sure how that fits in.  I'd be happy to add this with a PR if it's appropriate.

**Comment by mhegazy** [comment]
We have are currentlly generated this port of the dom directelly from the spec on W3C. the spec does not seem to mention anything about `userLanguage` see https://www.w3.org/TR/html51/webappapis.html#navigatorlanguage-navigatorlanguage.

if this is IE specific feature, consider defininig it locally in your prooject:

```ts
interface NavigatorLanguage  {
    userLanguage?: string;
}

```

**Comment by AlexanderEllis** [comment]
Thanks for the quick response! The use of the spec makes sense, and we'll implement a local workaround.
