### ISSUE TITLE
Missing overload for document.createElementNS() function

### ISSUE THREAD

**Issue by stevedorries** [Microsoft/TSJS-lib-generator#501]
The createElementNS function has an optional third parameter, options, that can be either a string(for backwards compatibility) or an object. The document.createElement() function already has an equivalent function overload being generated, createElement(tagName: string, options?: ElementCreationOptions): HTMLElement;. 
There should be an overload signature like this:
createElementNS(namespaceURI: string, qualifiedName: string, options?: ElementCreationOptions): Element; 

There are existing overloads for createElementNS located in the AddedTypes JSON file, but the overloads for createElement are in the emitter.ts file, this inconsistency raises the question, in my mind, where should the additional overload for createElementNS be located?

**Comment by mhegazy** [comment]
>  where should the additional overload for createElementNS be located?

addedTypes.json
