### ISSUE TITLE
`CanvasPathMethods` has been renamed `CanvasPath` [Breaking Change]

### ISSUE THREAD

**Issue by denisname** [Microsoft/TSJS-lib-generator#548]
When using typescript@next (Version 3.1.0-dev.20180801), it comes with a `lib.dom.d.ts` missing `CanvasPathMethods` interface. Apparently, the interface has been renamed `CanvasPath` but without the method:
```typescript
arcTo(x1: number, y1: number, x2: number, y2: number, radiusX: number, radiusY: number, rotation: number): void;
```
This creates a backward incompatibilty, see: https://github.com/DefinitelyTyped/DefinitelyTyped/pull/27750.

Please rename the interface back, add a _deprecated_ type alias `CanvasPathMethods` or propose a way I can upgrade a type definition.

**Comment by andy-ms** [comment]
It may be better to just define a new interface containing the particular methods that d3-shape needs.

**Comment by denisname** [comment]
Ok, thanks.
