### ISSUE TITLE
MediaQueryListListener should provide a MediaQueryListEvent

### ISSUE THREAD

**Issue by andy-ms** [Microsoft/TSJS-lib-generator#550]
In `typescript@3.0` this was:

```ts
interface MediaQueryListListener {
    (mql: MediaQueryList): void;
}
interface MediaQueryList {
    readonly matches: boolean;
    readonly media: string;
    addListener(listener: MediaQueryListListener): void;
    removeListener(listener: MediaQueryListListener): void;
}
```

As of Microsoft/TypeScript#25944 this is now:

```ts
interface MediaQueryList extends EventTarget {
	...
    addListener(listener: EventListenerOrEventListenerObject | null): void;
    ...
}
```

According to [mdn](https://developer.mozilla.org/en-US/docs/Web/API/MediaQueryList/addListener) this is better than before, but it could be more specific -- the event will always be a `MediaQueryListEvent`, but currently will just be an `Event`.

This affects `match-media-mock` on DefinitelyTyped.

**Comment by saschanaz** [comment]
Also the `addListener`/`removeListener` pair should be marked as deprecated as now the standard `add/removeEventListener` is preferred.

**Comment by SteppeEagle** [comment]
> Also the addListener/removeListener pair should be marked as deprecated as now the standard add/removeEventListener is preferred.

@saschanaz Where did you find that they should be deprecated?
In the standard there is no word about deprecation. 
https://drafts.csswg.org/cssom-view/#dom-mediaquerylist-addlistener

**Comment by saschanaz** [comment]
@SteppeEagle The deprecation in the web specification means it would generate a warning message in runtime when used, and the web people now don't want to use such mechanism. They instead marks a type as "historical, only for backward compatibility" and that's what we currently refer to add `@deprecated`.

[Per the spec](https://drafts.csswg.org/cssom-view/#dom-mediaquerylist-addlistener) they are historical:

>Note: This specification initially had a custom callback mechanism with addListener() and removeListener(), and the callback was invoked with the associated media query list as argument. Now the normal event mechanism is used instead. For backwards compatibility, the addListener() and removeListener() methods are basically aliases for addEventListener() and removeEventListener(), respectively, and the change event masquerades as a MediaQueryList.

**Comment by teleaziz** [comment]
This is related, https://github.com/angular/material2/issues/15264, Safari doesn't implement addEventListener/RemoveEventListener which leaves us no option but to use the `historical` APIs and redefine the `MediaQueryList` interface in our codebases .....

**Comment by krokofant** [comment]
@teleaziz Can't one just add a polyfill in case addEventListener doesn't exist?

**Comment by saschanaz** [comment]
Or maybe one can just add `// tslint:disable-next-line:deprecation` over the specific lines.
