### ISSUE TITLE
I can't override method.

### ISSUE THREAD

**Issue by YuichiNukiyama** [Microsoft/TSJS-lib-generator#63]
I want override ClipboardEvent.
So, I change overridingTypes.json and then run bat.
 But, Nothing is occured.

```javascript
{
        "kind": "method",
        "interface": "HTMLElement",
        "name": "onbeforecopy",
        "signatures": ["onbeforecopy: (ev: ClipboardEvent) => any"]
}
```
This promlem has occured at removeTypes.json.
[Lib.d.ts `addEventListener` should specify `ClipboardEvent` payload for relevant events #5363 ](https://github.com/Microsoft/TypeScript/issues/5363)

**Comment by mhegazy** [comment]
It is originally not defined as a method, but as a property. @zhengbli what is the recommendation here?

**Comment by YuichiNukiyama** [comment]
@mhegazy 
Thank's for your advise.It's my careless mistake. I was able to run if modified as follows.

```
    {
        "kind": "property",
        "interface": "HTMLElement",
        "name": "onbeforecopy",
        "type": "(ev: ClipboardEvent) => any"
    }
```
