### ISSUE TITLE
valueAsDate should be Date | null instead of any

### ISSUE THREAD

**Issue by azizhk** [Microsoft/TSJS-lib-generator#642]
From MDN: https://developer.mozilla.org/en-US/docs/Web/API/HTMLInputElement

In the current codebase:
https://github.com/Microsoft/TSJS-lib-generator/blob/ba752e1f6017ba9ab7ed7e9dea8a4903caef0d1e/inputfiles/idl/HTML%20-%20The%20input%20element.commentmap.json#L7

https://github.com/Microsoft/TSJS-lib-generator/blob/ba752e1f6017ba9ab7ed7e9dea8a4903caef0d1e/inputfiles/idl/HTML%20-%20The%20input%20element.widl#L38

I guess object gets converted to `any` when LKG gets updated in Typescript.
Can it be changed to Date | null? Or has the Typescript team found any browser inconsistencies?
has.js and Modernizr only check for `valueAsDate in document.createElement('input')` so I assume not undefined should be enough.
Let me know if ok and I'll create a PR.

😞 Sad a lot of developers don't use input[type="date"] due to inconsistency issues across browsers and limited standards to specify the format. https://developers.google.com/web/updates/2012/08/Quick-FAQs-on-input-type-date-in-Google-Chrome

**Comment by saschanaz** [comment]
Looks like a right change.
