### ISSUE TITLE
Webworker Headers missing entries()

### ISSUE THREAD

**Issue by 13rac1** [microsoft/TSJS-lib-generator#729]
Worker Header interface is missing the `entries()` method:
https://developer.mozilla.org/en-US/docs/Web/API/Headers/entries

> The Headers.entries() method returns an iterator allowing to go through all key/value pairs contained in this object. The both the key and value of each pairs are ByteString objects.

Problem is probably due to it being worker only.

> Note: This method is available in Web Workers.

It's not listed in the `fetch.widl` https://github.com/microsoft/TSJS-lib-generator/blob/a20c41802d11d47dbe27b09f0ad2c9f47a3db421/inputfiles/idl/Fetch.widl#L3-L12

Requires changes to `inputfiles/overridingTypes.json` to implement.

**Comment by saschanaz** [comment]
This is because we don't have `webworker.iterable.generated.d.ts`. We should create it.
