### ISSUE TITLE
Object.keys should return `keyof T`

### ISSUE THREAD

**Issue by bfred-it** [microsoft/TSJS-lib-generator#733]
Playground: https://www.typescriptlang.org/play/#src=const%20feature%20%3D%20%7B%0D%0A%09description%3A%20''%2C%0D%0A%09screenshot%3A%20''%2C%0D%0A%09disabled%3A%20''%0D%0A%7D%3B%0D%0A%0D%0Aconst%20keys%20%3D%20Object.keys(feature)%3B

```ts
const feature = {
	description: '',
	screenshot: '',
	disabled: ''
};

const list = Object.keys(feature);
```

## Current

```ts
keys(o: {}): string[];
```

```ts
typeof list = string[]
```

## Expected

```ts
keys<T extends object>(o: T): Array<keyof T>;
```

```ts
typeof list = Array<"description" | "screenshot" | "disabled">
```

## Workaround

```ts
const feature = {
	description: '',
	screenshot: '',
	disabled: ''
};

const list = Object.keys(feature) as Array<keyof typeof feature>;
```

**Comment by saschanaz** [comment]
Object.keys is not on TSJS-lib-generator. It should be directly fixed in TypeScript repo.

**Comment by bfred-it** [comment]
Indeed, moved to https://github.com/microsoft/TypeScript/issues/32321
