### ISSUE TITLE
MediaList.toString() returns a number

### ISSUE THREAD

**Issue by derekxu16** [microsoft/TSJS-lib-generator#795]
I noticed that in the MediaList interface .toString returns a number. Is this the intended behavior?

https://github.com/microsoft/TSJS-lib-generator/blob/fa29c3499084a4f74ee45b26be6f880fcf3ec9e3/baselines/dom.generated.d.ts#L9004

**Comment by saschanaz** [comment]
No, that seems erroneous.

**Comment by derekxu16** [comment]
Fixed by #754
