### ISSUE TITLE
Element.getAttribute's name parameter should not be optional

### ISSUE THREAD

**Issue by Arnavion** [Microsoft/TSJS-lib-generator#82]
The IDL XML seems to think the parameter is [optional with default of null,](https://github.com/Microsoft/TSJS-lib-generator/blob/04bb287/inputfiles/browser.webidl.xml#L3373) but it isn't according to [the spec.](https://dom.spec.whatwg.org/#interface-element) Indeed browsers complain if calling it without any parameters.

**Comment by mhegazy** [comment]
i think this is a internal implementation detail. We get this file from the IE/Edge folks, and i know their implementation relies on these value. 
I believe this reads as, an optional parameter, and if not specified, it is treated as null for the implementation of the function.
so for the caller, it is just optional.

**Comment by mhegazy** [comment]
> Indeed browsers complain if calling it without any parameters.

which browser is that? and what version? again it is possible that this is an inconsistency in IE/Edge.

**Comment by Arnavion** [comment]
Sorry, I should've clarified. I tested in FF Nightly (48) and Chrome Dev (51). IE 11 returns null, as you said. Didn't try Edge.

**Comment by mhegazy** [comment]
so it is a bug in the spec files we get from IE. Adding an entry to https://github.com/Microsoft/TSJS-lib-generator/blob/master/inputfiles/overridingTypes.json should solve the issue.

**Comment by mhegazy** [comment]
Thanks @YuichiNukiyama
