### ISSUE TITLE
Add Array.includes

### ISSUE THREAD

**Issue by 2426021684** [Microsoft/TSJS-lib-generator#90]
Add [Array.prototype.includes](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/includes)
```ts
interface Array<T>{
	includes(value: T, index?: number): boolean
}
```

**Comment by mhegazy** [comment]
it is already available in https://github.com/Microsoft/TypeScript/blob/master/lib/lib.es2016.array.include.d.ts.

Use `--lib es2016` to get the definition in your compilation. `--lib` is a new feature in TS 2.0, see https://github.com/Microsoft/TypeScript/issues/6974 for more information
