### ISSUE TITLE
Missing iterator types for HTMLCollectionBase and StyleSheetList

### ISSUE THREAD

**Issue by remcohaszing** [microsoft/TSJS-lib-generator#901]
The following types are missing from the `dom` lib:

```ts
interface HTMLCollectionBase {
  [Symbol.iterator]: () => Iterator<Element>;
}

interface StyleSheetList {
  [Symbol.iterator]: () => Iterator<CSSStyleSheet>;
}
```

This makes the following code work:

```ts
const nodes = [...document.body.children];
const currenStyleSheets = [...document.styleSheets];
```

There may be more similar cases I’m not aware of.

**Comment by saschanaz** [comment]
They both exist:

https://github.com/microsoft/TSJS-lib-generator/blob/099e2386881f54947e8689a4288b19dca577f43b/baselines/dom.iterable.generated.d.ts#L80-L82

https://github.com/microsoft/TSJS-lib-generator/blob/099e2386881f54947e8689a4288b19dca577f43b/baselines/dom.iterable.generated.d.ts#L223-L225

The code still doesn't work on the playground though. cc @orta

**Comment by remcohaszing** [comment]
Apparently this requires the `dom.iterable` lib in addition to `dom`. I think the issue can be closed.
