### ISSUE TITLE
onerror events should match addEventListener('error') event types

### ISSUE THREAD

**Issue by martine** [Microsoft/TSJS-lib-generator#94]
Filed as https://github.com/Microsoft/TypeScript/issues/8202 but I think it belongs here.

As of 59dc04933ddd77ffdc81c5005673dc50c7973e47 (current master) in many cases the `addEventListener("error", ...)` code uses a different event type from the `onerror` code.

E.g. I think these should be using `ErrorEvent` for the `onerror`, not `Event`, to match `addEventListener`.  (Perhaps it's intentional?)

```
interface MSBaseReader {
    onerror: (ev: Event) => any;
    addEventListener(type: "error", listener: (ev: ErrorEvent) => any, useCapture?: boolean): void;
```

```
interface IDBDatabase extends EventTarget {
    onerror: (ev: Event) => any;
    addEventListener(type: "error", listener: (ev: ErrorEvent) => any, useCapture?: boolean): void;
```

**Comment by zhengbli** [comment]
Fixed by https://github.com/Microsoft/TSJS-lib-generator/pull/108
