### ISSUE TITLE
Check overridden items for nullable types 

### ISSUE THREAD

**Issue by zhengbli** [Microsoft/TSJS-lib-generator#96]
Currently we don't check the nullability of types for items in the `overridingTypes.json`. We should check the nullability of the corresponding types in the spec and complement the content.

**Comment by saneyuki** [comment]
[`NonElementParentNode.getElementById()`](https://dom.spec.whatwg.org/#dom-nonelementparentnode-getelementbyid) has the nullability for the return value.
